#!/usr/bin/env bash

# ==============================================================================
# QueryCraft — 1-Click Universal MCP Installer
# Automatically configures Antigravity, Gemini, Cursor, & Claude Desktop
# ==============================================================================

set -e

GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[1;33m"
BOLD="\033[1m"
NC="\033[0m"

echo -e "${BOLD}${BLUE}"
echo "  ___                            ____            __ _   "
echo " / _ \ _   _  ___ _ __ _   _    / ___|_ __ __ _ / _| |_ "
echo "| | | | | | |/ _ \ '__| | | |  | |   | '__/ _\` | |_| __|"
echo "| |_| | |_| |  __/ |  | |_| |  | |___| | | (_| |  _| |_ "
echo " \__\_\\\\__,_|\___|_|   \__, |   \____|_|  \__,_|_|  \__|"
echo "                      |___/                             "
echo -e "${NC}"
echo -e "${BOLD}QueryCraft MCP 1-Click Installer (Antigravity · Gemini · Cursor · Claude)${NC}\n"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="${SCRIPT_DIR}/backend"

# 1. Resolve Python executable
PYTHON_BIN=""
if [ -f "${BACKEND_DIR}/.venv/bin/python" ]; then
    PYTHON_BIN="${BACKEND_DIR}/.venv/bin/python"
elif [ -f "${BACKEND_DIR}/venv/bin/python" ]; then
    PYTHON_BIN="${BACKEND_DIR}/venv/bin/python"
elif command -v uv &>/dev/null; then
    PYTHON_BIN="$(which uv) run python"
else
    PYTHON_BIN="$(which python3)"
fi

echo -e "✓ Found Python environment: ${GREEN}${PYTHON_BIN}${NC}"
echo -e "✓ Found QueryCraft Backend: ${GREEN}${BACKEND_DIR}${NC}\n"

# Python helper to safely inject/merge MCP config into JSON files
inject_mcp_config() {
    local target_file="$1"
    local app_name="$2"

    mkdir -p "$(dirname "${target_file}")"

    python3 - <<PYEOF
import json, os

target = "${target_file}"
backend = "${BACKEND_DIR}"
py_bin = "${PYTHON_BIN}"

mcp_entry = {
    "command": py_bin,
    "args": ["-m", "app.mcp_server"],
    "cwd": backend,
    "env": {
        "PYTHONPATH": backend,
        "READ_ONLY_ENFORCED": "true",
        "AUTO_LIMIT": "50"
    }
}

data = {}
if os.path.exists(target) and os.path.getsize(target) > 0:
    try:
        with open(target, "r") as f:
            data = json.load(f)
    except Exception:
        data = {}

if "mcpServers" not in data or not isinstance(data["mcpServers"], dict):
    data["mcpServers"] = {}

data["mcpServers"]["querycraft-cost-guard"] = mcp_entry

with open(target, "w") as f:
    json.dump(data, f, indent=2)

print("  ✓ Configured ${app_name} at: " + target)
PYEOF
}

# 2. Configure Antigravity / Gemini
echo -e "${BOLD}Detecting and configuring AI agents...${NC}"
ANTIGRAVITY_CONFIG="${HOME}/.gemini/config/mcp_config.json"
inject_mcp_config "${ANTIGRAVITY_CONFIG}" "Google Antigravity & Gemini"

# 3. Configure Cursor IDE (Global & Project-local)
CURSOR_GLOBAL="${HOME}/.cursor/mcp.json"
inject_mcp_config "${CURSOR_GLOBAL}" "Cursor IDE (Global)"

PROJECT_CURSOR="${SCRIPT_DIR}/.cursor/mcp.json"
inject_mcp_config "${PROJECT_CURSOR}" "Cursor IDE (Project Workspace)"

# 4. Configure Claude Desktop if present
CLAUDE_DIR="${HOME}/Library/Application Support/Claude"
if [ -d "${CLAUDE_DIR}" ]; then
    CLAUDE_CONFIG="${CLAUDE_DIR}/claude_desktop_config.json"
    inject_mcp_config "${CLAUDE_CONFIG}" "Claude Desktop"
fi

# 5. Verify the MCP server runs
echo -e "\n${BOLD}Verifying MCP server startup...${NC}"
if "${PYTHON_BIN}" -c "import app.mcp_server; print('  ✓ MCP Server syntax and tools verified successfully!')" 2>/dev/null; then
    echo -e "${GREEN}✓ QueryCraft MCP Server verified successfully!${NC}"
else
    echo -e "${YELLOW}⚠️ MCP Server imported with warnings. Please verify backend dependencies.${NC}"
fi

# 6. Install 'querycraft' as a global CLI command
echo -e "\n${BOLD}Installing querycraft CLI...${NC}"
LOCAL_BIN="${HOME}/.local/bin"
mkdir -p "${LOCAL_BIN}"
CLI_TARGET="${LOCAL_BIN}/querycraft"

# Write a wrapper script that always runs from the correct venv
cat > "${CLI_TARGET}" << CLIEOF
#!/usr/bin/env sh
# querycraft CLI wrapper — auto-generated by setup-mcp.sh
cd "${BACKEND_DIR}"
exec "${PYTHON_BIN}" "${BACKEND_DIR}/cli.py" "\$@"
CLIEOF
chmod +x "${CLI_TARGET}"

# Check if ~/.local/bin is on PATH
if echo ":${PATH}:" | grep -q ":${LOCAL_BIN}:"; then
    echo -e "${GREEN}  ✓ querycraft installed → ${CLI_TARGET}${NC}"
else
    echo -e "${GREEN}  ✓ querycraft installed → ${CLI_TARGET}${NC}"
    echo -e "${YELLOW}  ⚠ Add this to your shell profile to use it globally:${NC}"
    echo -e "    ${BOLD}echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc && source ~/.zshrc${NC}"
fi

echo -e "\n${BOLD}${GREEN}========================================================================${NC}"
echo -e "${BOLD}${GREEN}🎉 Setup Complete! QueryCraft MCP is now installed.${NC}"
echo -e "${BOLD}${GREEN}========================================================================${NC}\n"
echo -e "${BOLD}Step 1 — Authenticate your account (once):${NC}"
echo -e "  ${CYAN}querycraft auth login${RESET}          # Opens browser → sign in → done\n"
echo -e "${BOLD}Step 2 — Use in Antigravity, Cursor, or Claude:${NC}"
echo -e "  💬 ${BOLD}\"List my available QueryCraft workspaces\"${NC}"
echo -e "  💬 ${BOLD}\"Switch to my Analytics workspace\"${NC}"
echo -e "  💬 ${BOLD}\"Check the compute cost and run: SELECT * FROM users;\"${NC}\n"
echo -e "${DIM}Other CLI commands:${NC}"
echo -e "  querycraft auth whoami      # See current logged-in user"
echo -e "  querycraft auth logout      # Sign out"
echo -e "  querycraft workspaces list  # List all database workspaces\n"

